// Code generated by godddx, DO AVOID EDIT.
package sms

import (
	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/web"
)

type FindMediaServerInput struct {
	web.PagerFilter
	IP                string           `form:"ip"`
	HookIP            string           `form:"hook_ip"`
	SDPIP             string           `form:"sdpip"`
	StreamIP          string           `form:"stream_ip"`
	Ports             MediaServerPorts `form:"ports"`
	AutoConfig        bool             `form:"auto_config"`
	Secret            string           `form:"secret"`
	HookAliveInterval int              `form:"hook_alive_interval"`
	RTPEnable         bool             `form:"rtpenable"`
	Status            bool             `form:"status"`
	RTPPortRange      string           `form:"rtpport_range"`
	SendRTPPortRange  string           `form:"send_rtpport_range"`
	RecordAssistPort  int              `form:"record_assist_port"`
	LastKeepaliveAt   orm.Time         `form:"last_keepalive_at"`
	IsDefault         bool             `form:"is_default"`
	RecordDay         int              `form:"record_day"`
	RecordPath        string           `form:"record_path"`
	Type              string           `form:"type"`
	TranscodeSuffix   string           `form:"transcode_suffix"`
}

type EditMediaServerInput struct {
	IP     string `json:"ip"`
	HookIP string `json:"hook_ip"`
	SDPIP  string `json:"sdp_ip"`
	// StreamIP          string           `json:"stream_ip"`
	// Ports MediaServerPorts `json:"ports"`
	// AutoConfig        bool             `json:"auto_config"`
	Secret string `json:"secret"`
	Type   string `json:"type"` // lalmax/zlm
	// HookAliveInterval int              `json:"hook_alive_interval"`
	// RTPEnable         bool             `json:"rtpenable"`
	// Status            bool             `json:"status"`
	// RTPPortRange     string   `json:"rtpport_range"`
	// SendRTPPortRange string   `json:"send_rtpport_range"`
	// RecordAssistPort int      `json:"record_assist_port"`
	// LastKeepaliveAt orm.Time `json:"last_keepalive_at"`
	// IsDefault       bool     `json:"is_default"`
	// RecordDay       int      `json:"record_day"`
	// RecordPath      string   `json:"record_path"`
	// Type            string `json:"type"`
	// TranscodeSuffix string `json:"transcode_suffix"`
}

type AddMediaServerInput struct {
	IP                string           `json:"ip"`
	HookIP            string           `json:"hook_ip"`
	SDPIP             string           `json:"sdpip"`
	StreamIP          string           `json:"stream_ip"`
	Ports             MediaServerPorts `json:"ports"`
	AutoConfig        bool             `json:"auto_config"`
	Secret            string           `json:"secret"`
	HookAliveInterval int              `json:"hook_alive_interval"`
	RTPEnable         bool             `json:"rtpenable"`
	Status            bool             `json:"status"`
	RTPPortRange      string           `json:"rtpport_range"`
	SendRTPPortRange  string           `json:"send_rtpport_range"`
	RecordAssistPort  int              `json:"record_assist_port"`
	LastKeepaliveAt   orm.Time         `json:"last_keepalive_at"`
	IsDefault         bool             `json:"is_default"`
	RecordDay         int              `json:"record_day"`
	RecordPath        string           `json:"record_path"`
	Type              string           `json:"type"`
	TranscodeSuffix   string           `json:"transcode_suffix"`
}
